//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "song_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub requested_song_id: i32,
    pub user_id: i32,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::requested_spotify_songs::Entity",
        from = "Column::RequestedSongId",
        to = "super::requested_spotify_songs::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    RequestedSpotifySongs,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::requested_spotify_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RequestedSpotifySongs.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
